export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import Footer from "@/_lib/Footer";
import "./globals.css";
import NavBar from "@/_lib/NvBar";
import PocketBase from "pocketbase";

// Check who's logged in
//Cart == logged in order with status = 0
//On product added, create an order
const db = new PocketBase("http://localhost:8090/");


export default function RootLayout({
  children,
  db
}: {
  children: React.ReactNode;
  db : PocketBase
}) {
  return (
    <html lang="en">
      <head>
        <title>
          Farm Shop
        </title>
      </head>
      <body>
        <div className="w-full">
          <NavBar />
        </div>
        {0 ? (
          <div className=" bg-purple-400 flex">
            <div className="w-full text-white">Free ice cream on summer</div>
          </div>
        ) : null}

        <main
          className="flex-auto w-full min-w-0 lg:static lg:max-h-full lg:overflow-visible
        border border-black"
        >
          {children}
        </main>
        <div>
          <footer>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
